export const GET_NOTES = "GET";
export const ADD_NOTE = "ADD_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const CLEAR_NOTES = "CLEAR_NOTES";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const FILTER_NOTES = "FILTER_NOTES";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const NOTE_ERROR = "NOTE_ERROR";

GET_NOTES,
ADD_NOTE ,
DELETE_NOTE, 
SET_CURRENT,
CLEAR_CURRENT ,
CLEAR_NOTES ,
UPDATE_NOTE ,
FILTER_NOTES ,
CLEAR_FILTER ,
SET_ALERT ,
REMOVE_ALERT, 
NOTE_ERROR ,